timeout: 0

/R4OS
    protocol: limine
    path: boot():/boot/r4os.elf
    module_path: boot():/boot/preload.r4i
    module_string: r4os.preload.image=PRELOAD.R4I
    module_path: boot():/boot/preload/hidreport.r4p
    module_string: r4os.preload.usb-r4p=HIDREPORT
    module_path: boot():/boot/preload/usbhid.r4p
    module_string: r4os.preload.usb-r4p=USBHID
    module_path: boot():/boot/preload/usbbot.r4p
    module_string: r4os.preload.usb-r4p=USBBOT
    module_path: boot():/boot/preload/usbscsi.r4p
    module_string: r4os.preload.usb-r4p=USBSCSI
    resolution: 1280x720x32

/R4OS Previous Kernel
    protocol: limine
    path: boot():/boot/r4os-prev.elf
    module_path: boot():/boot/preload.r4i
    module_string: r4os.preload.image=PRELOAD.R4I
    module_path: boot():/boot/preload/hidreport.r4p
    module_string: r4os.preload.usb-r4p=HIDREPORT
    module_path: boot():/boot/preload/usbhid.r4p
    module_string: r4os.preload.usb-r4p=USBHID
    module_path: boot():/boot/preload/usbbot.r4p
    module_string: r4os.preload.usb-r4p=USBBOT
    module_path: boot():/boot/preload/usbscsi.r4p
    module_string: r4os.preload.usb-r4p=USBSCSI
    resolution: 1280x720x32
