// Host witness using the same ZIP core, package reader, NTFS reader and plan
// as the guest. Inputs are generated by the real PowerShell/.NET producers.
const std = @import("std");
const r4os = @import("r4os");
const package = @import("package.zig");
const source = @import("system_source.zig");
const nv = @import("ntfs_volume");
const ntfs = r4os.storage_tools.ntfs_format;
const core = @import("zip_core");
const expect = std.testing.expect;
const Codec = struct {
    pub fn inspect(_: Codec, bytes: []const u8, entries: []r4os.zip.Entry) !r4os.zip.Info {
        return core.inspect(bytes, entries);
    }
    pub fn begin(_: Codec, bytes: []const u8, entry: *const r4os.zip.Entry, output: []u8, work: *r4os.zip.Work) !r4os.zip.Progress {
        return core.begin(bytes, entry.*, output, &work.data);
    }
    pub fn step(_: Codec, work: *r4os.zip.Work, budget: u32) !r4os.zip.Progress {
        return core.step(&work.data, budget);
    }
};
const Memory = struct {
    bytes: []u8,
    writes: usize = 0,
    fn read(raw: *anyopaque, lba: u64, out: []u8) i32 {
        const self: *Memory = @ptrCast(@alignCast(raw));
        if (lba > self.bytes.len / 512 or out.len > self.bytes.len - lba * 512) return -1;
        @memcpy(out, self.bytes[@intCast(lba * 512)..][0..out.len]);
        return 0;
    }
    fn write(raw: *anyopaque, lba: u64, data: []const u8) i32 {
        const self: *Memory = @ptrCast(@alignCast(raw));
        if (lba > self.bytes.len / 512 or data.len > self.bytes.len - lba * 512) return -1;
        self.writes += 1;
        @memcpy(self.bytes[@intCast(lba * 512)..][0..data.len], data);
        return 0;
    }
    fn flush(_: *anyopaque) i32 {
        return 0;
    }
    fn readNv(raw: *anyopaque, lba: u64, count: u32, out: []u8) bool {
        return count * 512 == out.len and read(raw, lba, out) == 0;
    }
    fn noWrite(_: *anyopaque, _: u64, _: u32, _: []const u8) bool {
        return false;
    }
    fn noFlush(_: *anyopaque) bool {
        return false;
    }
};
pub fn main(init: std.process.Init) !void {
    const a = init.arena.allocator();
    const args = try init.minimal.args.toSlice(a);
    if (args.len == 3 and std.mem.eql(u8, args[1], "--shrink-fixture")) {
        // The private host fixture has a 16-MB GPT extent but a freshly built
        // 32-MB NTFS in otherwise unused space. Shrink its metadata to the
        // declared extent before any guest can see the fixture.
        const image = try std.Io.Dir.cwd().readFileAlloc(init.io, args[2], a, .limited(2048 * 1024 * 1024 + 1));
        try expect(image.len == 2048 * 1024 * 1024);
        var memory = r4os.storage_tools.io.Memory{ .bytes = image };
        const work = try a.alloc(u8, r4os.storage_tools.io.scratch_bytes);
        var table = try r4os.storage_tools.partition.Plan.read(memory.device(), work);
        try expect(table.entries[2].count == 16 * 2048);
        const shrink = try r4os.storage_tools.ntfs_resize.Plan.prepare(a, memory.device(), &table, 3, 32 * 2048, work);
        try shrink.execute(memory.device(), &table, work);
        try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = args[2], .data = image });
        std.debug.print("[PACKAGEHOST] fixture_system=16MB valid_ntfs=SHRUNK\n", .{});
        return;
    }
    if (args.len == 4 and std.mem.eql(u8, args[1], "--updated-system")) {
        const zip = try std.Io.Dir.cwd().readFileAlloc(init.io, args[2], a, .limited(package.max_archive_bytes));
        const prepared = try package.prepare(a, Codec{}, zip, .r4os, .{});
        const tree = try source.Tree.read(a, prepared.archive.get("disk.img").?, prepared.version(), .{});
        const image = try std.Io.Dir.cwd().readFileAlloc(init.io, args[3], a, .limited(32 * 1024 * 1024 * 1024));
        var disk = Memory{ .bytes = image };
        const work = try a.alloc(u8, r4os.storage_tools.io.scratch_bytes);
        const table = try r4os.storage_tools.partition.Plan.read(.{ .context = &disk, .sectors = image.len / 512, .read_fn = Memory.read, .write_fn = Memory.write, .flush_fn = Memory.flush }, work);
        try expect(table.kind == .gpt and table.entries[2].present);
        const part = table.entries[2];
        var volume_bytes = Memory{ .bytes = image[@intCast(part.first * 512)..][0..@intCast(part.count * 512)] };
        const scratch = try a.create(nv.Scratch);
        scratch.* = .{};
        const runs = try a.alloc(ntfs.Run, nv.MAX_MFT_RUNS);
        const device = nv.Device{ .ctx = &volume_bytes, .read_sectors = Memory.readNv, .write_sectors = Memory.noWrite, .flush = Memory.noFlush };
        const mounted = nv.mount(device, 0, scratch, runs) orelse return error.TargetMount;
        var count = mounted.mft_run_count;
        const volume = nv.Volume{ .device = device, .partition_lba = 0, .cluster_bytes = mounted.cluster_bytes, .record_bytes = mounted.record_bytes, .index_block_bytes = mounted.index_block_bytes, .total_sectors = mounted.total_sectors, .mft_runs_buf = runs, .mft_run_count = &count, .upcase = r4os.storage_tools.standardNtfsMetadata().upcase, .scratch = scratch };
        try expect(mounted.total_sectors + 1 == part.count and !(nv.isDirty(&volume) orelse return error.TargetDirty));
        for (tree.nodes.items, 0..) |node, i| {
            const record = if (i == 0) ntfs.MFT_RECORD_ROOT else blk: {
                const entry = nv.resolveEntry(&volume, node.path) orelse return error.TargetEntry;
                try expect(entry.entry.isDir() == node.directory and (node.directory or entry.entry.size == node.data.len));
                break :blk entry.entry.record;
            };
            if (node.directory) {
                var expected_children: usize = 0;
                for (tree.nodes.items[1..]) |child| if (child.parent == i) {
                    expected_children += 1;
                };
                for (0..expected_children + 1) |wanted| {
                    var sink = nv.EnumSink{ .wanted = wanted };
                    try expect(nv.enumerateDirectory(&volume, record, &sink));
                    try expect((sink.found != null) == (wanted < expected_children));
                }
            } else {
                var offset: usize = 0;
                while (offset < node.data.len) {
                    const amount = @min(work.len, node.data.len - offset);
                    try expect((nv.readFileRange(&volume, record, offset, work[0..amount]) orelse return error.TargetRead) == amount);
                    try std.testing.expectEqualSlices(u8, node.data[offset..][0..amount], work[0..amount]);
                    offset += amount;
                }
            }
        }
        try expect(volume_bytes.writes == 0 and disk.writes == 0);
        std.debug.print("[PACKAGEHOST] updated_system={s} sectors={d} nodes={d} exact_tree=OK writes=0\n", .{ prepared.version(), part.count, tree.nodes.items.len });
        return;
    }
    if (args.len == 3 and std.mem.eql(u8, args[1], "--installation")) {
        const bytes = try std.Io.Dir.cwd().readFileAlloc(init.io, args[2], a, .limited(package.max_archive_bytes));
        const prepared = try package.prepare(a, Codec{}, bytes, .r4os, .{});
        const tree = try source.Tree.read(a, prepared.archive.get("disk.img").?, prepared.version(), .{});
        try source.verifyInstallation(a, prepared, tree, .{});
        var mismatch = prepared;
        mismatch.system.?.kernelVersion = "99.99.99";
        try std.testing.expectError(error.SourceVersion, source.verifyInstallation(a, mismatch, tree, .{}));
        mismatch = prepared;
        mismatch.recovery.recoveryKernelVersion = "99.99.99";
        try std.testing.expectError(error.SourceKernel, source.verifyRecovery(a, mismatch));
        const outer_kernel = @constCast(prepared.archive.get("BOOT/boot/r4os.elf").?);
        outer_kernel[0] ^= 1;
        try std.testing.expectError(error.SourceContentMismatch, source.verifyInstallation(a, prepared, tree, .{}));
        outer_kernel[0] ^= 1;
        std.debug.print("[PACKAGEHOST] installation={s} profile={s} files={d} coherent=OK mismatches=REJECTED writes=0\n", .{ prepared.version(), prepared.system.?.profile, tree.nodes.items.len });
        return;
    }
    if (args.len != 4) return error.Usage;
    const cwd = std.Io.Dir.cwd();
    const recovery_zip = try cwd.readFileAlloc(init.io, args[1], a, .limited(package.max_archive_bytes));
    const system_zip = try cwd.readFileAlloc(init.io, args[2], a, .limited(package.max_archive_bytes));
    const recovery = try package.prepare(a, Codec{}, recovery_zip, .recovery, .{});
    try expect(recovery.kind == .recovery);
    if (package.peek(a, Codec{}, recovery_zip, .r4os, .{})) |_| return error.WrongKindAccepted else |_| {}
    var no_ram: [1]u8 = undefined;
    var fail = std.heap.FixedBufferAllocator.init(&no_ram);
    try std.testing.expectError(error.OutOfMemory, package.prepare(fail.allocator(), Codec{}, recovery_zip, .recovery, .{}));
    const system = try package.prepare(a, Codec{}, system_zip, .r4os, .{});
    const tree = try source.Tree.read(a, system.archive.get("disk.img").?, system.version(), .{});
    if (tree.prepareTarget(a, 266240, 8 * 2048, 55, .{})) |_| return error.SmallTargetAccepted else |_| {}
    var target = try tree.prepareTarget(a, 266240, 32 * 2048, 55, .{});
    defer target.deinit();
    try expect(target.plan.bytes == 32 * 1024 * 1024 and target.plan.used_clusters < target.plan.clusters);
    const bytes = try a.alloc(u8, 32 * 1024 * 1024);
    var memory = Memory{ .bytes = bytes };
    const work = try a.alloc(u8, 128 * 1024);
    try target.plan.execute(.{ .context = &memory, .sectors = bytes.len / 512, .exclusive = true, .read_fn = Memory.read, .write_fn = Memory.write, .flush_fn = Memory.flush }, true, work);
    try expect(memory.writes > 0);
    const scratch = try a.create(nv.Scratch);
    scratch.* = .{};
    const runs = try a.alloc(ntfs.Run, nv.MAX_MFT_RUNS);
    const device = nv.Device{ .ctx = &memory, .read_sectors = Memory.readNv, .write_sectors = Memory.noWrite, .flush = Memory.noFlush };
    const mounted = nv.mount(device, 0, scratch, runs) orelse return error.TargetMount;
    var count = mounted.mft_run_count;
    const volume = nv.Volume{ .device = device, .partition_lba = 0, .cluster_bytes = mounted.cluster_bytes, .record_bytes = mounted.record_bytes, .index_block_bytes = mounted.index_block_bytes, .total_sectors = mounted.total_sectors, .mft_runs_buf = runs, .mft_run_count = &count, .upcase = r4os.storage_tools.standardNtfsMetadata().upcase, .scratch = scratch };
    try expect((mounted.total_sectors + 1) * 512 == bytes.len);
    try expect(!(nv.isDirty(&volume) orelse return error.TargetDirty));
    for (tree.nodes.items[1..]) |node| {
        const entry = nv.resolveEntry(&volume, node.path) orelse return error.TargetEntry;
        try expect(entry.entry.isDir() == node.directory);
        if (node.directory) continue;
        try expect(entry.entry.size == node.data.len);
        var at: usize = 0;
        while (at < node.data.len) {
            const amount = @min(work.len, node.data.len - at);
            try expect((nv.readFileRange(&volume, entry.entry.record, at, work[0..amount]) orelse return error.TargetRead) == amount);
            try std.testing.expectEqualSlices(u8, node.data[at..][0..amount], work[0..amount]);
            at += amount;
        }
    }
    try cwd.writeFile(init.io, .{ .sub_path = args[3], .data = bytes });
    std.debug.print("[PACKAGEHOST] recovery={s} r4os={s} files={d} file_bytes={d} target_bytes={d} used_clusters={d} original_zip_retained=yes result=OK\n", .{ recovery.version(), system.version(), tree.nodes.items.len - 1, tree.file_bytes, bytes.len, target.plan.used_clusters });
}
