const types = @import("../key_layout_types.zig");

const kc = types.KeyChar;

const aliases = [_][]const u8{
    "DE",
    "DE_DE",
    "DE-DE",
    "GERMAN",
    "GERMANY",
    "QWERTZ",
};

const entries = [_]types.KeyEntry{
    .{ .scancode = 0x01, .normal = kc.asciiChar(0x1B), .shift = kc.asciiChar(0x1B) },
    .{ .scancode = 0x02, .normal = kc.asciiChar('1'), .shift = kc.asciiChar('!') },
    .{ .scancode = 0x03, .normal = kc.asciiChar('2'), .shift = kc.asciiChar('"'), .altgr = kc.unicode(0x00B2) },
    .{ .scancode = 0x04, .normal = kc.asciiChar('3'), .shift = kc.unicode(0x00A7), .altgr = kc.unicode(0x00B3) },
    .{ .scancode = 0x05, .normal = kc.asciiChar('4'), .shift = kc.asciiChar('$') },
    .{ .scancode = 0x06, .normal = kc.asciiChar('5'), .shift = kc.asciiChar('%') },
    .{ .scancode = 0x07, .normal = kc.asciiChar('6'), .shift = kc.asciiChar('&') },
    .{ .scancode = 0x08, .normal = kc.asciiChar('7'), .shift = kc.asciiChar('/'), .altgr = kc.asciiChar('{') },
    .{ .scancode = 0x09, .normal = kc.asciiChar('8'), .shift = kc.asciiChar('('), .altgr = kc.asciiChar('[') },
    .{ .scancode = 0x0A, .normal = kc.asciiChar('9'), .shift = kc.asciiChar(')'), .altgr = kc.asciiChar(']') },
    .{ .scancode = 0x0B, .normal = kc.asciiChar('0'), .shift = kc.asciiChar('='), .altgr = kc.asciiChar('}') },
    .{ .scancode = 0x0C, .normal = kc.unicode(0x00DF), .shift = kc.asciiChar('?'), .altgr = kc.asciiChar('\\') },
    .{ .scancode = 0x0D, .normal = kc.unicodeAscii(0x00B4, '\''), .shift = kc.asciiChar('`') },
    .{ .scancode = 0x0E, .normal = kc.asciiChar(0x08), .shift = kc.asciiChar(0x08) },
    .{ .scancode = 0x0F, .normal = kc.asciiChar('\t'), .shift = kc.asciiChar('\t') },
    .{ .scancode = 0x10, .normal = kc.asciiChar('q'), .shift = kc.asciiChar('Q'), .altgr = kc.asciiChar('@') },
    .{ .scancode = 0x11, .normal = kc.asciiChar('w'), .shift = kc.asciiChar('W') },
    .{ .scancode = 0x12, .normal = kc.asciiChar('e'), .shift = kc.asciiChar('E'), .altgr = kc.unicode(0x20AC) },
    .{ .scancode = 0x13, .normal = kc.asciiChar('r'), .shift = kc.asciiChar('R') },
    .{ .scancode = 0x14, .normal = kc.asciiChar('t'), .shift = kc.asciiChar('T') },
    .{ .scancode = 0x15, .normal = kc.asciiChar('z'), .shift = kc.asciiChar('Z') },
    .{ .scancode = 0x16, .normal = kc.asciiChar('u'), .shift = kc.asciiChar('U') },
    .{ .scancode = 0x17, .normal = kc.asciiChar('i'), .shift = kc.asciiChar('I') },
    .{ .scancode = 0x18, .normal = kc.asciiChar('o'), .shift = kc.asciiChar('O') },
    .{ .scancode = 0x19, .normal = kc.asciiChar('p'), .shift = kc.asciiChar('P') },
    .{ .scancode = 0x1A, .normal = kc.unicode(0x00FC), .shift = kc.unicode(0x00DC) },
    .{ .scancode = 0x1B, .normal = kc.asciiChar('+'), .shift = kc.asciiChar('*'), .altgr = kc.asciiChar('~') },
    .{ .scancode = 0x1C, .normal = kc.asciiChar('\n'), .shift = kc.asciiChar('\n') },
    .{ .scancode = 0x1E, .normal = kc.asciiChar('a'), .shift = kc.asciiChar('A') },
    .{ .scancode = 0x1F, .normal = kc.asciiChar('s'), .shift = kc.asciiChar('S') },
    .{ .scancode = 0x20, .normal = kc.asciiChar('d'), .shift = kc.asciiChar('D') },
    .{ .scancode = 0x21, .normal = kc.asciiChar('f'), .shift = kc.asciiChar('F') },
    .{ .scancode = 0x22, .normal = kc.asciiChar('g'), .shift = kc.asciiChar('G') },
    .{ .scancode = 0x23, .normal = kc.asciiChar('h'), .shift = kc.asciiChar('H') },
    .{ .scancode = 0x24, .normal = kc.asciiChar('j'), .shift = kc.asciiChar('J') },
    .{ .scancode = 0x25, .normal = kc.asciiChar('k'), .shift = kc.asciiChar('K') },
    .{ .scancode = 0x26, .normal = kc.asciiChar('l'), .shift = kc.asciiChar('L') },
    .{ .scancode = 0x27, .normal = kc.unicode(0x00F6), .shift = kc.unicode(0x00D6) },
    .{ .scancode = 0x28, .normal = kc.unicode(0x00E4), .shift = kc.unicode(0x00C4) },
    .{ .scancode = 0x29, .normal = kc.asciiChar('^'), .shift = kc.unicode(0x00B0) },
    .{ .scancode = 0x2B, .normal = kc.asciiChar('#'), .shift = kc.asciiChar('\'') },
    .{ .scancode = 0x2C, .normal = kc.asciiChar('y'), .shift = kc.asciiChar('Y') },
    .{ .scancode = 0x2D, .normal = kc.asciiChar('x'), .shift = kc.asciiChar('X') },
    .{ .scancode = 0x2E, .normal = kc.asciiChar('c'), .shift = kc.asciiChar('C') },
    .{ .scancode = 0x2F, .normal = kc.asciiChar('v'), .shift = kc.asciiChar('V') },
    .{ .scancode = 0x30, .normal = kc.asciiChar('b'), .shift = kc.asciiChar('B') },
    .{ .scancode = 0x31, .normal = kc.asciiChar('n'), .shift = kc.asciiChar('N') },
    .{ .scancode = 0x32, .normal = kc.asciiChar('m'), .shift = kc.asciiChar('M'), .altgr = kc.unicode(0x00B5) },
    .{ .scancode = 0x33, .normal = kc.asciiChar(','), .shift = kc.asciiChar(';') },
    .{ .scancode = 0x34, .normal = kc.asciiChar('.'), .shift = kc.asciiChar(':') },
    .{ .scancode = 0x35, .normal = kc.asciiChar('-'), .shift = kc.asciiChar('_') },
    .{ .scancode = 0x39, .normal = kc.asciiChar(' '), .shift = kc.asciiChar(' ') },
    .{ .scancode = 0x56, .normal = kc.asciiChar('<'), .shift = kc.asciiChar('>'), .altgr = kc.asciiChar('|') },
};

pub const definition = types.LayoutDefinition{
    .id = .de_de,
    .name = "de_de",
    .display = "DE",
    .aliases = aliases[0..],
    .entries = entries[0..],
};
